services:
  - type: web
    name: karanka-deriv
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: karanka_db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1

databases:
  - name: karanka_db
    plan: free
    databaseName: karanka
    user: karanka_user
