services:
  - type: web
    name: karanka-deriv-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --worker-class=sync --timeout=120 --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
      - key: WEB_CONCURRENCY
        value: 2
    healthCheckPath: /health
    autoDeploy: true
