services:
  - type: web
    name: karanka-deriv-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000
    healthCheckPath: /
    autoDeploy: true
    domains:
      - karanka-deriv.onrender.com
